### ISSUE TITLE
Baselines

### ISSUE THREAD

**Issue by IfrahIdrees** [UM-ARM-Lab/Efficient-Eng-2-LTL#1]
Hello Jiayi,

We met during ICRA's poster session. I wanted to ask if you can add to the repo the baseline setup for RNN[6]. I would like to see what modifications were required, if any, to handle a larger dataset. Thank you!

Best,
Ifrah

**Comment by Jiayi-Pan** [comment]
Hi IfrahIdrees,

Thank you for your inquiry.

For the RNN baseline, we have adopted it directly from the official implementation found in the paper, [Sequence-to-Sequence Language Grounding of Non-Markovian Task Specifications](https://www.semanticscholar.org/paper/Sequence-to-Sequence-Language-Grounding-of-Task-Gopalan-Arumugam/4f82413cfc46d99897f2dddec7933fca0df83d0c). You can review the associated code at [this GitHub repository](https://github.com/h2r/lggltl/blob/master/models/torch/torch_seq2seq.py). All of its hyperparameters have been preserved or adjusted to align with the specifications outlined in the original paper.

As for the CopyNet implementation, our version is based on the model discussed in [the original paper](https://ieeexplore.ieee.org/document/9197068). However, since there was no publicly accessible code for it, I created a custom reproduction which can be found at [this repository](https://github.com/Jiayi-Pan/CopyNet).

If your inquiry relates specifically to our model proposed in this repository, I believe the model should perform adequately without any modifications, assuming the dataset isn't significantly larger. If the dataset is substantially larger, a practical suggestion would be to experiment with a stronger base-model such as T5-XXL, and possibly extend the training duration to achieve better results. Please let me know if you have any issue with that :)

However, if your objective is to use the CopyNet/RNN model to handle a larger dataset for any reason, my guess is that it might be beneficial to increase the model's capacity. Additionally, re-tuning the hyper-parameters to fit the larger dataset may also contribute to improved performance.

Please let me know if you have any further questions or need additional clarification.

**Comment by rtk29** [comment]
Hi Jiayi,

I am trying to use the semantic parsing code for my use case for parsing purposes referenced from "https://github.com/microsoft/semantic_parsing_with_constrained_lm". However, the IDE throws an error of unable to find the above said module "ModuleNotFoundError: No module named 'semantic_parsing_with_constrained_lm'".

How did you import that module?

**Comment by Jiayi-Pan** [comment]
> Hi Jiayi,
> 
> 
> 
> I am trying to use the semantic parsing code for my use case for parsing purposes referenced from "https://github.com/microsoft/semantic_parsing_with_constrained_lm". However, the IDE throws an error of unable to find the above said module "ModuleNotFoundError: No module named 'semantic_parsing_with_constrained_lm'".
> 
> 
> 
> How did you import that module?

Hi could you open another issue for the problem you mention and provide more details on reproducing your python environment. I am happy to help!

**Comment by rtk29** [comment]
Hi,

I opened another issue for this problem and shared the problem I am facing with a snapshot. Thanks in advance
